name: Simple Python Build

# teste

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Check out the code
        uses: actions/checkout@v4

      - name: Set up Python 3.9
        uses: actions/setup-python@v4
        with:
          python-version: "3.9"

      - name: Run tests
        run: python -m unittest discover -s tests

      - name: Package application
        run: |
          python setup.py sdist bdist_wheel
          mkdir dist_package && cp dist/* dist_package

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: Python Package
          path: dist_package
